server:
  port: 5000
  servlet:
    session.cookie.name: b8a5f3fb
  forward-headers-strategy: native

spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url}
    username: ${db.username}
    password: ${db.password}
  devtools:
    livereload:
      enabled: false

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddlAuto: ${ddl.auto}

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB
      fileSizeThreshold: 30MB

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${mail.username} # 이메일 아이디, 주소가 test@gmail.com이면 test
    password: ${mail.password} # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 - 기본값 false
          timeout: 5000 # Socket Read Timeout 시간(ms) - 기본값 : 무한대
          starttls:
            enable: true # StartTLS 활성화 여부 - 기본값 false

# 로깅 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

# 파일 업로드 경로 설정
file:
  upload:
    url: ${file.url}
    path: ${file.path}


# 파이썬 설정
python:
  path:
    base: ${python.base}
    emotion: ${python.emotion}


# 소셜 로그인
social:
  kakao.apikey: ${kakao.apikey}
  naver.apikey: ${naver.apikey}
  naver.secret: ${naver.secret}